### PR TITLE
Merge in Upstream

### PR DESCRIPTION
**Pull request by donovanbray**

### CODE REVIEW

**Comment by RealNobody** [comment]
There appears to be a merge conflict - You'll have to resolve that.

Also, why did we fork this?  Can we not use the maintained gem?

**Comment by donovanbray** [comment]
some minor changes were made to it back in the day, we don't even need it anymore. I just wanted our fork to have the deprecation messages.  I'll need to do the merge manually.

**Comment by RealNobody** [comment]
> we don't even need it anymore.

If we don't need it anymore, I say just delete the fork myself.

**Comment by donovanbray** [comment]
It would break master and prod-rel and any number of branches that still depend on it if we just deleted the repo.  It's also a public repo, with at least one follower, so I want the deprecation message so people don't fork it thinking it's still current.

**Pull request merged**
